# Generated by Django 5.1.6 on 2025-02-21 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primerapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='joined_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='priority',
            field=models.IntegerField(null=True),
        ),
    ]
